spring:
  # Data source
  datasource:
    url: {MYSQL_URL}
    username: {MYSQL_USER}
    password: {MYSQL_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8

  # Thymeleaf
  thymeleaf:
    cache: false

  # Session
  session:
    store-type: redis

  # Redis
  redis:
    host: localhost
    port: 6379
    password: {REDIS_PASSWORD}

# Logging
logging:
  config: classpath:log4j2-local.yaml
